BUTTON_TEXTS_BY_LOCALE = {
    "ru": {
        "start_server_user": "🚀 Запустить сервер",
        "start_server_admin": "🟢 Запустить сервер 🟢",
        "stop_server_admin": "🔴 Остановить сервер 🔴",
        "online": "👥 Онлайн на сервере",
        "user_settings": "⚙️ Мои настройки",
        "admin_settings": "⚙️ Настройки",
        "reload_bot": "🔄 Перезапустить бота",
        "console": "📟 Консоль",
        "workload": "📊 Нагрузка сервера",
        "server_properties": "🧩 Свойства сервера",
        "profile": "👤 Профиль",
        "back": "⬅️ Назад",
        "test": "test",
        "users_list": "📋 Список пользователей",
        "add_user": "➕ Добавить пользователя",
        "remove_user": "➖ Удалить пользователя",
        "permissions": "🔒 Права доступа",
        "disable_start_notifications": "🟢 Выключить уведомления о запуске",
        "enable_start_notifications": "🔴 Включить уведомления о запуске",
    },
    "en": {
        "start_server_user": "🚀 Start Server",
        "start_server_admin": "🟢 Start Server 🟢",
        "stop_server_admin": "🔴 Stop Server 🔴",
        "online": "👥 Players Online",
        "user_settings": "⚙️ My Settings",
        "admin_settings": "⚙️ Settings",
        "reload_bot": "🔄 Restart Bot",
        "console": "📟 Console",
        "workload": "📊 Server Load",
        "server_properties": "🧩 Server Properties",
        "profile": "👤 Profile",
        "back": "⬅️ Back",
        "test": "test",
        "users_list": "📋 Users List",
        "add_user": "➕ Add User",
        "remove_user": "➖ Remove User",
        "permissions": "🔒 Permissions",
        "disable_start_notifications": "🟢 Disable startup notifications",
        "enable_start_notifications": "🔴 Enable startup notifications",
    },
}

KEYBOARD_LAYOUTS = {
    "user_main_offline": [["start_server_user"], ["user_settings", "test"]],
    "user_main_online": [["online"], ["user_settings", "test"]],
    "user_settings": [["profile"], ["back"]],
    "admin_main_offline": [["start_server_admin"], ["online", "console"], ["admin_settings", "reload_bot"]],
    "admin_main_online": [["stop_server_admin"], ["online", "console"], ["admin_settings", "reload_bot"]],
    "admin_settings": [["server_properties", "workload"], ["back"]],
    "admin_console": [["back"]],
    "admin_users": [["users_list"], ["add_user", "remove_user"], ["permissions"], ["back"]],
}
